export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const GET_INGREDIENTS = "GET_INGREDIENTS";
export const FETCH_INGREDIENTS_FAIL = "FETCH_INGREDIENTS_FAIL";

export const STORE_BURGER_ORDER = "STORE_BURGER_ORDER";
export const PURCHASE_BURGER_ERROR = "PURCHASE_BURGER_ERROR";
export const LOADING_ORDER = "LOADING_ORDER";
export const REDIRECT_TO_HOME = "REDIRECT_TO_HOME";
