export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const GET_INGREDIENTS = "GET_INGREDIENTS";
export const FETCH_INGREDIENTS_FAIL = "FETCH_INGREDIENTS_FAIL";

export const STORE_BURGER_ORDER = "STORE_BURGER_ORDER";
export const PURCHASE_BURGER_ERROR = "PURCHASE_BURGER_ERROR";
export const LOADING_ORDER = "LOADING_ORDER";
export const PURCHASE_INIT = "PURCHASE_INIT";
export const LOADING_ALL_ORDERS = "LOADING_ALL_ORDERS";
export const FETCH_ORDERS_INIT = "FETCH_ORDERS_INIT";
export const FAIL_ORDER_INIT = "FAIL_ORDER_INIT";
